version: '3.8'

services:
  # Backend API Service
  todoapp-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todoapp-api
    restart: unless-stopped
    ports:
      - "5232:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DATABASE_CONNECTION_STRING=Data Source=/app/data/todoapp.db
    volumes:
      - todoapp-data:/app/data
    networks:
      - todoapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/graphql"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  todoapp-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_GRAPHQL_ENDPOINT=http://localhost:5232/graphql
    container_name: todoapp-web
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - todoapp-backend
    networks:
      - todoapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Named volumes for data persistence
volumes:
  todoapp-data:
    driver: local

# Networks
networks:
  todoapp-network:
    driver: bridge